Typo

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -19,6 +19,6 @@ jobs:
         run: |
           if [[ "$GITHUB_HEAD_REF" != 'dev' ]]
           then
-            echo "ERROR: Only PR's from dev branch are allowed." `>&2
+            echo "ERROR: Only PR's from dev branch are allowed." 1>&2
             exit 1
           fi
